#!/bin/sh

useremail=$(git config user.email)
files=$(git diff --cached --name-only)

for file in $files
do
    case "$file" in
        APP.API/*)
            if [ "$useremail" = "armagantambova@gmail.com" ]; then
                echo "❌ $useremail kullanıcısı APP.API klasörüne commit atamaz!"
                exit 1
            fi
            ;;
    esac
done

exit 0